version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/todo/client/
hooks:
  AfterInstall:
#    - location: scripts/start_server
#      timeout: 300
#      runas: ec2-user
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: ec2-user
