image: node:7.4
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm --version
  branches:
    staging:
      - step:
          image: python:3.5.1
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3==1.3.0 # required for codedeploy_deploy.py
            - zip -9 -r /tmp/artifact.zip * # package up the application for deployment
            - python codedeploy_deploy.py # run the deployment script
